class Locators:
    username = "//input[@id='authUser']"
    password = "//input[@id='clearPass']"
    lang_dd = "//select[@name='languageChoice']"
    select_lang = "//option[text()='English (Indian)']"
    login_button = "//button[@id='login-button']"
    patient_button = "//div[normalize-space()='Patient']"
    patient_new_search = "//div[text()='New/Search']"
    fst_name = "//input[@id='form_fname']"
    lst_name = "//input[@id='form_lname']"
    DOB_field = "//input[@id='form_DOB']"
    DOB_today = "(//td[contains(@class, 'xdsoft_today')])[1]"
    gender_dropdown = "//select[@id='form_gender_identity']"
    gender_selection = "//option[text()='Identifies as Male']"
    create_button = "//button[@id='create']"